name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2 
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
          
    - uses: getong/mariadb-action@v1.1
      with:
        mysql database: TamagochiTypes_db
        mysql root password: ${{ secrets.RootPassword }} 
        mysql user: root
        mysql password:  ${{ secrets.RootPassword }} 
        
    - name: Build with Maven
      run:  mvn -B verify
      
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GIITHUB_TOKEN }} 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=stenneyrinck_3APP01-APT-Back_TypesTomagotchi_Microservice
      
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Docker Build
      run: docker build -t ${{ secrets.DOCKER_USER }}/types-tamagotchi:latest .
      
    - name: Upload container to Docker Hub with Push
      run: docker push ${{ secrets.DOCKER_USER }}/types-tamagotchi:latest
